apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot
  namespace: dev
spec:
  rules:
    - host: iot.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iot
                port:
                  number: 4000